# CS 363D Final Project: Predicting Adoption in Austin Animal Center

## Mrityunjay Mishra, Rohit Neppalli, Ziyi Zhao, Justin Leong 

### Project Description

Many different types of animals (from dogs to livestock) are taken in by the Austin Animal Center each year for various reasons. Some may be adopted, some may be transferred, and some may even go through Euthanasia. The goal of this project is to predict if an animal, that is taken in by the Austin Animal Center, will be adopted or not. This can have good applications for Austin Animal Center - they could use our findings to predict the probability of adoption for an animal that is taken in and can care for it accordingly. Or perhaps someone else can use our findings to find animals who have a low probability of adoption to care for them accordingly. In the end, we hope that our findings provide insight into the adoption patterns of Austin and, consequently, helps different organizations take care of these animal appropriately.

In [3]:
# importing headers
import random
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Enable inline mode for matplotlib so that IPython displays graphs.
%matplotlib inline

### Dataset

To develop our classifier(s), we use the animal intake and outcome data from the open data portal of the city of Austin. To find our more about the animal intake data, [click here](https://data.austintexas.gov/Health-and-Community-Services/Austin-Animal-Center-Intakes/wter-evkm). To find out more about the outcome data, [click here](https://data.austintexas.gov/Health-and-Community-Services/Austin-Animal-Center-Outcomes/9t4d-g238). 

In [4]:
# Intakes data
intakes_df = pd.read_csv('Austin_Animal_Center_Intakes.csv')
intakes_df.head()

Animal ID     Name                DateTime     MonthYear  \
0   A786884   *Brock  01/03/2019 04:19:00 PM  January 2019   
1   A706918    Belle  07/05/2015 12:59:00 PM     July 2015   
2   A724273  Runster  04/14/2016 06:43:00 PM    April 2016   
3   A665644      NaN  10/21/2013 07:59:00 AM  October 2013   
4   A682524      Rio  06/29/2014 10:38:00 AM     June 2014   

                        Found Location Intake Type Intake Condition  \
0  2501 Magin Meadow Dr in Austin (TX)       Stray           Normal   
1     9409 Bluegrass Dr in Austin (TX)       Stray           Normal   
2   2818 Palomino Trail in Austin (TX)       Stray           Normal   
3                          Austin (TX)       Stray             Sick   
4        800 Grove Blvd in Austin (TX)       Stray           Normal   

  Animal Type Sex upon Intake Age upon Intake  \
0         Dog   Neutered Male         2 years   
1         Dog   Spayed Female         8 years   
2         Dog     Intact Male       11 months   
3         Cat   Intact Female         4 weeks   
4         Dog   Neutered Male         4 years   

                                   Breed        Color  
0                             Beagle Mix     Tricolor  
1               English Springer Spaniel  White/Liver  
2                            Basenji Mix  Sable/White  
3                 Domestic Shorthair Mix       Calico  
4  Doberman Pinsch/Australian Cattle Dog     Tan/Gray

In [5]:
# Outcomes data
outcomes_df = pd.read_csv('Austin_Animal_Center_Outcomes.csv')
outcomes_df.head()

Animal ID   Name                DateTime MonthYear Date of Birth  \
0   A794011  Chunk  05/08/2019 06:20:00 PM  May 2019    05/02/2017   
1   A776359  Gizmo  07/18/2018 04:02:00 PM  Jul 2018    07/12/2017   
2   A821648    NaN  08/16/2020 11:38:00 AM  Aug 2020    08/16/2019   
3   A720371  Moose  02/13/2016 05:59:00 PM  Feb 2016    10/08/2015   
4   A674754    NaN  03/18/2014 11:47:00 AM  Mar 2014    03/12/2014   

  Outcome Type Outcome Subtype Animal Type Sex upon Outcome Age upon Outcome  \
0    Rto-Adopt             NaN         Cat    Neutered Male          2 years   
1     Adoption             NaN         Dog    Neutered Male           1 year   
2   Euthanasia             NaN       Other          Unknown           1 year   
3     Adoption             NaN         Dog    Neutered Male         4 months   
4     Transfer         Partner         Cat      Intact Male           6 days   

                                Breed              Color  
0              Domestic Shorthair Mix  Brown Tabby/White  
1             Chihuahua Shorthair Mix        White/Brown  
2                             Raccoon               Gray  
3  Anatol Shepherd/Labrador Retriever               Buff  
4              Domestic Shorthair Mix       Orange Tabby

## Data Cleaning And Feature Engineering

##### 1. Clean data and combine features

- Drop `Name`, `Date of Birth`, `Outcome Subtype`, `DateTime` in outcome dataframe.
- Drop `Name`, `DateTime`, `Found Location` in intake dataframe.
- Encode categorical variables `Outcome Type`, `Animal Type`, `Sex upon Outcome`, `Breed`, `Color` using `factorize` from `pandas`.
- Encode categorical variables `Intake Type`, `Intake Condition` `Animal Type`, `Sex upon Intake`, `Breed`, `Color` using `factorize` from `pandas`.
- Add column `Outcome Age (Years)` in outcome dataframe using data from column `Age upon Outcome`.
- Add column `Intake Age (Years)` in intake dataframe using data from column `Age upon Intake`.
- Add encoded column `Intake Month` in intake dataframe using data from column `MonthYear`.
- Add encoded column `Outcome Month` in outcome dataframe using data from column `MonthYear`.
- Drop columns that contains `NaN` in intake and outcome dataframe.

In [6]:
# Do some basic data prep / cleaning
outcomes_df = outcomes_df.drop(columns=['Name', 'Date of Birth', 'Outcome Subtype', 'DateTime'])
cat_columns = ['Outcome Type', 'Animal Type', 'Sex upon Outcome', 'Breed', 'Color']
outcomes_df[cat_columns] = outcomes_df[cat_columns].apply(lambda x: pd.factorize(x)[0])
outcomes_df.dropna(inplace=True)

intakes_df = intakes_df.drop(columns=['Name', 'DateTime', 'Found Location'])
cat_columns = ['Intake Type', 'Intake Condition', 'Animal Type', 'Sex upon Intake', 'Breed', 'Color']
intakes_df[cat_columns] = intakes_df[cat_columns].apply(lambda x: pd.factorize(x)[0])
intakes_df.dropna(inplace=True)

def standardize_age(age):
  if 'month' in age:
    return 0
  if 'year' in age:
    return int(age.split(' ')[0])
  if 'day' in age:
    return 0
  return 0

outcomes_df['Outcome Age (Years)'] = outcomes_df['Age upon Outcome'].apply(lambda x: standardize_age(x))
outcomes_df['Outcome Month'] = outcomes_df['MonthYear'].apply(lambda x: x.split(' ')[0])
outcomes_df['Outcome Month'] = outcomes_df['Outcome Month'].map(lambda x: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'].index(x) + 1)
outcomes_df['Outcome Year'] = outcomes_df['MonthYear'].apply(lambda x: x.split(' ')[1])
outcomes_df = outcomes_df.drop(columns=['Age upon Outcome', 'MonthYear'])

intakes_df['Intake Age (Years)'] = intakes_df['Age upon Intake'].apply(lambda x: standardize_age(x))
intakes_df['Intake Month'] = intakes_df['MonthYear'].apply(lambda x: x.split(' ')[0])
intakes_df['Intake Month'] = intakes_df['Intake Month'].map(lambda x: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'].index(x) + 1)
intakes_df['Intake Year'] = intakes_df['MonthYear'].apply(lambda x: x.split(' ')[1])
intakes_df = intakes_df.drop(columns=['Age upon Intake', 'MonthYear'])

# A lot of different breeds, may not be a useful metric for classification problems

intakes_df

Animal ID  Intake Type  Intake Condition  Animal Type  Sex upon Intake  \
0        A786884            0                 0            0                0   
1        A706918            0                 0            0                1   
2        A724273            0                 0            0                2   
3        A665644            0                 1            1                3   
4        A682524            0                 0            0                0   
...          ...          ...               ...          ...              ...   
138345   A855584            0                 0            0                4   
138346   A855586            2                 0            0                2   
138347   A855589            0                 0            0                4   
138348   A821095            2                 0            0                1   
138349   A855557            0                 0            0                3   

        Breed  Color  Intake Age (Years)  Intake Month Intake Year  
0           0      0                   2             1        2019  
1           1      1                   8             7        2015  
2           2      2                   0             4        2016  
3           3      3                   0            10        2013  
4           4      4                   4             6        2014  
...       ...    ...                 ...           ...         ...  
138345      9    100                   1             4        2022  
138346      9      8                   2             4        2022  
138347     35      6                   2             4        2022  
138348    136      8                   2             8        2020  
138349      8     18                   5             4        2022  

[138350 rows x 10 columns]

##### 2. Merge intake and outcome data

- Merge intake and outcome dataframe based on `Animal ID` using `merge` from `pandas`.
- Drop column `Anmial ID` and we have the combined dataframe.

In [7]:
# Combine together into singular dataframe\
combined_df = intakes_df.merge(outcomes_df[['Animal ID', 'Outcome Type', 'Sex upon Outcome', 'Outcome Age (Years)', 'Outcome Month', 'Outcome Year']], on='Animal ID')
combined_df = combined_df.drop('Animal ID', axis=1)
combined_df

Intake Type  Intake Condition  Animal Type  Sex upon Intake  Breed  \
0                 0                 0            0                0      0   
1                 0                 0            0                1      1   
2                 0                 0            0                2      2   
3                 0                 1            1                3      3   
4                 0                 0            0                0      4   
...             ...               ...          ...              ...    ...   
178565            1                 0            0                1    182   
178566            0                 0            0                3    182   
178567            0                 0            0                3    182   
178568            2                 0            0                1    136   
178569            0                 0            0                3      8   

        Color  Intake Age (Years)  Intake Month Intake Year  Outcome Type  \
0           0                   2             1        2019             3   
1           1                   8             7        2015             4   
2           2                   0             4        2016             4   
3           3                   0            10        2013             3   
4           4                   4             6        2014             4   
...       ...                 ...           ...         ...           ...   
178565     16                   4             1        2018             1   
178566     16                   4            10        2017             1   
178567     16                   4            10        2017             1   
178568      8                   2             8        2020             3   
178569     18                   5             4        2022             4   

        Sex upon Outcome  Outcome Age (Years)  Outcome Month Outcome Year  
0                      0                    2              1         2019  
1                      3                    8              7         2015  
2                      0                    1              4         2016  
3                      4                    0             10         2013  
4                      0                    4              7         2014  
...                  ...                  ...            ...          ...  
178565                 3                    4             12         2017  
178566                 3                    4              1         2018  
178567                 3                    4             12         2017  
178568                 3                    2              8         2020  
178569                 4                    5              4         2022  

[178570 rows x 14 columns]

## Decision Trees Nested Cross Validation

In [8]:
# Try out some classification approaches, with outcome type as the label
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeClassifier

decision_tree = DecisionTreeClassifier(criterion='entropy')
grid_params = {
    'max_depth': [5, 8, 13], 
    'min_samples_leaf': [5, 10, 15, 20], 
    'max_features': [5, 8, 13]
}
grid_search = GridSearchCV(decision_tree, grid_params, cv=5, scoring='accuracy')
grid_search.fit(combined_df.drop('Outcome Type', axis=1), combined_df['Outcome Type'])
print(grid_search.best_params_)
print(grid_search.best_score_)

{'max_depth': 13, 'max_features': 13, 'min_samples_leaf': 20}
0.718860950887607


In [9]:
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import cross_val_predict

predictions = cross_val_predict(grid_search, combined_df.drop('Outcome Type', axis=1), combined_df['Outcome Type'])
print(confusion_matrix(combined_df['Outcome Type'], predictions))

[[    0     0    15     4     3    11     0     1     0     0]
 [    0    13   970     4    66   589     1     0     0     0]
 [    0    39 70761   139  3469  8607     2     5     0     0]
 [    0     0   854  5995  1726   856     7    45     0     0]
 [    0     5 12539   705 24456  6063    12    15     0     0]
 [    0    13  7747   211  3438 27081     1     2     0     0]
 [    0     1   170   260   803    89     9     8     0     0]
 [    0     0    15   454    95    20     0    53     0     0]
 [    0     0    23     2    35    39     0     0     0     0]
 [    0     0     7    14     2     1     0     0     0     0]]


In [10]:
combined_df['Outcome Type'].value_counts()

 1    83022
 3    43795
 4    38493
 2     9483
 0     1643
 5     1340
 6      637
 7       99
-1       34
 8       24
Name: Outcome Type, dtype: int64